package com.aswbalap.helloworld;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/test") // This means URL's start with /demo (after Application path)
public class TestController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TestRepository testRepository;

  @PostMapping(path="") // Map ONLY POST Requests
  @ResponseBody
  public String addNewTest (@RequestBody Test test) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Test t = new Test();
    t.setName(test.getName());
    testRepository.save(t);
    return "Saved";
  }

  @GetMapping(path="")
  public @ResponseBody Iterable<Test> getAllTests() {
    // This returns a JSON or XML with the users
    return testRepository.findAll();
  }
}